### ISSUE TITLE
blank page error

### ISSUE THREAD

**Issue by marianoear** [IOC/moodle-local_mail#18]
I have installed:
Moodle version: 2.6.4+ (Build: 20140724)
Mail version: 0.1.2

And the plugin was working excelent, but now some users (not all) see a blank page wen they go to indbox page (for example: http://MYSITE/local/mail/view.php?t=inbox).
Also web tey redact an email press sent and see a blank page (this is the link page example: http://MYSITE/local/mail/view.php?t=course&c=76).

I didn't change server preferences or configuration.

Please help me or guide me to try to fix this problem.
Thanks

**Comment by reskit** [comment]
First of all you need to check Apache error logs to find out what's happening, then we'll try to solve the problem.

**Comment by reskit** [comment]
Which version are you using now? 1.2?, I'll recommend you use last version available 1.6, because it resolves a lot of bugs.

**Comment by marianoear** [comment]
Hello, reskit
I'll check Apache's logs, I can`t upload to 1.6 version before Uploag Moodle 1.6 latest version.

**Comment by marianoear** [comment]
We found the problem, was memory_limint configuration in php.ini file.
