### ISSUE TITLE
No update of recipient's list

### ISSUE THREAD

**Issue by chnicolas** [IOC/moodle-local_mail#23]
I discovered an issue in last version (release = '1.8.1', version = 2016011200). 
Sometimes, recipient's list is not updated.
When a teacher add new users in a course, the list in local_mail recipients is not always updated.
Thus, there's a difference between participant's list in a course and recipient's list in local_mail (for the same course).
You can see screenshots below.
Participants in course 
![course_participants](https://cloud.githubusercontent.com/assets/11214742/15316276/832f6306-1c1c-11e6-8635-2f575aac33f4.png)

Recipients in local_mail
![recipients_localmail](https://cloud.githubusercontent.com/assets/11214742/15316283/8f1beb3a-1c1c-11e6-98c1-003e9ab18a78.png)

**Comment by reskit** [comment]
Sorry for my late reply.
Seems a problem related to MUC.
New users appears later in course? or never?
