### ISSUE TITLE
Missing menu link in 3.1

### ISSUE THREAD

**Issue by patriclougheed** [IOC/moodle-local_mail#24]
Two sites I upgraded recently to 3.1 and the menu for My Mail has gone.

![mail](https://cloud.githubusercontent.com/assets/1463351/16605187/c8399b7e-42e1-11e6-942b-adc3f9006806.jpg)

Did I miss something?

**Comment by reskit** [comment]
Are you using last version of Mail? (1.8.2), it's the only one that works under Moodle 3.1

**Comment by patriclougheed** [comment]
Weird thing is I had 1.7.5 and was not being informed of available updates from moodle.org. When I manually copy the new files over there is no prompt to update the database. Seems to be working though... thanks.
