### ISSUE TITLE
No get_unread_count_parameters function in external.php crashes API functions pages

### ISSUE THREAD

**Issue by infinitesunrise** [IOC/moodle-local_mail#25]
Hey there, was troubleshooting a client's Moodle trying to figure out why admin/webservice/documentation.php and admin/webservice/service_functions.php?action=add weren't loading correctly and throwing the error "missing parameters". Turns out it's because they had local_mail installed and your API function get_unread_count has no corresponding get_unread_count_parameters function. I added one myself, into classes/external.php, and that fixed the issue. I'm a bit too busy at the moment to create a proper pull request, but figure this info should be all you need to fix!

**Comment by reskit** [comment]
Hi!,

Thanks for reporting the bug, we're aware of it and it's fixed in master branch (https://github.com/IOC/moodle-local_mail/commit/35dcb1f451c95ac812a7d2eb4cbb198190b8d175).

We're going to release a new version of Mail shortly with that fix.
