### ISSUE TITLE
Attachments doesn't show when receiving mail with local_mail plugin

### ISSUE THREAD

**Issue by memetoec** [IOC/moodle-local_mail#26]
We are upgrading Moodle from 3.1 to Moodle 3.3 for a client, they use local_mail and have issues with attachments for this plugin.

It worked in 3.1, but after upgrading the dev environment it stopped working. They get the mail, all text are sent but there is a white space below the text where the picture should be. 

![githubissue_localmail](https://user-images.githubusercontent.com/9047962/37597870-ea4858a2-2b80-11e8-9b9e-a3ebd89a10a5.png)

I've checked the database and can see that the file has been uploaded and is registered in the "message" filearea. 

![githubissue_dbproof](https://user-images.githubusercontent.com/9047962/37598042-628e3c3c-2b81-11e8-9402-0f21862d4956.png)

Is this a known issue for Moodle version 3.3 and above?

**Comment by reskit** [comment]
Hi,

Which version of Mail are you using? Have you upgraded Mail from a previous version? 

Depending on your Mail version, you've to check the database and confirm attachments are created in Mail table (last version, 1.9.5 stores number of attachments in mdl_local_mail_messages).

Check your server error output after sending a message with attachments, maybe some error is thrown and it will help us to solve your problem.

We are using Moodle 3.3.X in our site and Mail is working fine.

**Comment by memetoec** [comment]
Thanks for you reply!

I have checked the messages that should contain attachments and they have the value "1". 
I also did a live test to send a mail with an attachment while listening on my error-log and there where no output during the test.

Are there any settings in Moodle that should be configured for the plugin to work? We have PHP configured to let us upload 2GB so it's not a limit issue generated by PHP.

**Comment by reskit** [comment]
Check Mail settings, Site Administration > Plugins > Local plugins > Mail and check maxbytes setting, by default is 1MB.

Try to raise debug level to Developer, something is happening and it's not showing up.

Have you tried to upload a file in a course or an activity? it's only to discard a problem more general. 

I'm sorry not being more helpful, but without an error it's difficult to guess whats the problem.

**Comment by reskit** [comment]
Hi @memetoec ,

You were right, there was a problem in Mail, not allowing users to send attachments and choose a group when Mail was configured to use only new navigation.

I've fixed the code and released a new version of Mail (1.9.6) dc34cee89dc474f16ea1836d94e1af271e0890c5, thanks for reporting the bug!
