### ISSUE TITLE
Replying to a message with a subject of 100 characters generates a database error

### ISSUE THREAD

**Issue by Kisa-chan** [IOC/moodle-local_mail#27]
When trying to reply to a message whose subject is exactly 100 characters long we get this error:

==================================================================

Debug info: Data too long for column 'subject' at row 1
UPDATE mdl_local_mail_messages SET subject = ?,content = ?,format = ?,attachments = ?,time = ? WHERE id=?
[array (
0 => 'RE: Bienvenida "Curso de Propiedad Intelectual para inventores, científicos y diseñadores industriales”',
1 => '',
2 => -1,
3 => 0,
4 => 1536855169,
5 => 220706,
)]
Error code: dmlwriteexception 

==================================================================

The work around we plan to use is to set the subject to 255 characters but I think this might require a validation.
By the way we are working with Moodle 3.5

**Comment by reskit** [comment]
Hi @Kisa-chan,

Thanks for reporting the bug. I've updated master branch to solve the problem.

Your workaround is the best way to solve the problem until you update Mail to last version 5b58519701389a8c8a16f22efbfa04dd395eed9e.
