### ISSUE TITLE
[ERROR] Subject too long

### ISSUE THREAD

**Issue by xcesaralejandro** [IOC/moodle-local_mail#29]
Cuando el usuario escribe un subject muy largo y este correo se va respondiendo, se agrega "RE: " al subject. 
Cuando esta cadena supera los 100 caracteres definidos en la tabla el correo en particular ya no funciona más, lanzando una excepción de moodle.

Se pueden aumentar los caracteres de subject para la base de datos pero esto no soluciona el problema, solo da un margen mayor antes de recibir el error.

Si usted lo decea, puedo crear un pull request truncando el asunto a 96 caracteres y agregando "..." al final.

---------------------------------

When the user writes a very long topic and this email is answered, "RE:" is added to the topic.
When this string exceeds 100 characters excluded in the table, the particular mail no longer works, throwing a moodle exception.

You can increase the subject characters for the database, but this does not solve the problem, it only gives a larger margin before receiving the error.

If you wish, I can create an pull request by truncating the subject to 96 characters and adding "..." at the end.

**Comment by reskit** [comment]
Hi,

This issue was resolved in 1.9.8 version

If you need to backport the patch to a previous version, please use 593bfdb commit.

For future bugs/features please use https://gitlab.com/reskity/moodle-local_mail, this GitHub repository is no longer maintained by me.

Thanks!
